config/routes.rb
Rails.application.routes.draw do
	resources :game_sessions
	resources :players
	resources :wands
	resources :durations
	resources :effects
	devise_for :users, :controllers => { registrations: 'registrations' }
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get '/settings' => 'statics#user_settings'
	get '/sessions' => 'game_sessions#my_sessions'
	get '/dm' => 'statics#dm_page'
	get '/p' => 'statics#player_page'
	root 'statics#dashboard'
end

app/models/game_session.rb
class GameSession < ApplicationRecord

	def self.new_session_player(session_id, number_of_players)
		    Rails.logger.info "Players Create" + session_id.to_s + " | " + number_of_players.to_s
			for a in 1..number_of_players do
				Rails.logger.info a.to_s
				Player.create(:name => "Unnamed Player_" + rand(100).to_s, :session_id => session_id.to_i, :status => "1", :unique_link => generate_unique_secure_token)
			end
	end

end

app/controllers/game_sessions_controller.rb
class GameSessionsController < ApplicationController
  before_action :set_game_session, only: [:show, :edit, :update, :destroy]
  after_action :check_admin, only: [:index]

  # GET /game_sessions
  # GET /game_sessions.json
  def index
    @game_sessions = GameSession.all

    if params[:reset] == 'true' and current_user.admin == true
      Rails.logger.info "==================================="
      Rails.logger.info "Redirect Settings - All Sessions reset"
      Rails.logger.info "==================================="
      GameSession.delete_all
      redirect_to game_sessions_path
    end
  end

  def my_sessions
    @game_sessions = GameSession.where(owner: current_user)
  end

  # GET /game_sessions/1
  # GET /game_sessions/1.json
  def show
  end

  # GET /game_sessions/new
  def new
    @game_session = GameSession.new
    # @generated_code = generate_token
    @effect_buffer = 3
    @number_of_players = 4
  end

  # GET /game_sessions/1/edit
  def edit
    @generated_code = @game_session.passcode
    @number_of_players = @game_session.number_of_players
    @effect_buffer = @game_session.effect_buffer
  end

  # POST /game_sessions
  # POST /game_sessions.json
  def create
    params[:game_session][:passcode] = generate_token
    @game_session = GameSession.new(game_session_params)

    Rails.logger.info "Session Create - Players " + @game_session.number_of_players.to_s

    respond_to do |format|
      if @game_session.save
        format.html { redirect_to @game_session, notice: 'Game session was successfully created.' }
        format.json { render :show, status: :created, location: @game_session }
      else
        format.html { render :new }
        format.json { render json: @game_session.errors, status: :unprocessable_entity }
      end

      GameSession.new_session_player(@game_session.id, @game_session.number_of_players)
    
    end
  end

  # PATCH/PUT /game_sessions/1
  # PATCH/PUT /game_sessions/1.json
  def update
    respond_to do |format|
      if @game_session.update(game_session_params)
        format.html { redirect_to @game_session, notice: 'Game session was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_session }
      else
        format.html { render :edit }
        format.json { render json: @game_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_sessions/1
  # DELETE /game_sessions/1.json
  def destroy
    @game_session.destroy
    respond_to do |format|
      format.html { redirect_to game_sessions_url, notice: 'Game session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_game_session
      @game_session = GameSession.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_session_params
      params.require(:game_session).permit(:session_name, :owner, :number_of_players, :effects_used, :passcode, :effect_buffer, :lock_player_pages, :player_display_mode)
    end
end

app/helpers/game_sessions_helper.rb
module GameSessionsHelper
end

app/views/game_sessions/_form.html.erb
<%= form_with(model: game_session, local: true) do |form| %>
<% if game_session.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(game_session.errors.count, "error") %> prohibited this game_session from being saved:</h2>

  <ul>
    <% game_session.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form.label :session_name %>
<%= form.text_field :session_name %>

<% if current_user.present? || @owner != 0 %>
<%= form.hidden_field :owner, value: current_user.id %>
<% else %>
<%= form.hidden_field :owner, value: 0 %>
<% end %>

<%= form.label :number_of_players %>
<%= form.number_field :number_of_players, :value => @number_of_players, min: 1, max: 10 %>
<%= form.hidden_field :passcode, value: @generated_code %>

<%= form.label :effect_buffer %>
<%= form.number_field :effect_buffer, :value => @effect_buffer, min: 1, max: 5%>
<div>
  <div class="cell">
    lock player pages <%= form.check_box :lock_player_pages, class: 'float-left' %>
  </div>
  <hr>
  <div class="cell">
    player display mode <%= form.check_box :player_display_mode, class: 'float-left' %>
  </div>
</div>
<%= form.submit %>
<% end %>

app/views/game_sessions/edit.html.erb
<div class="cell">
	<h3>Editing Game Session</h3>
</div>
<div>
<%= render 'form', game_session: @game_session %>
</div>
<div class="cell">
<%= link_to 'Show', @game_session %> |
<%= link_to 'Back', game_sessions_path %>
</div>

app/views/game_sessions/index.html.erb
<%= link_to "Reset All Sessions", {:controller => "game_sessions", :action => "index", :reset => true }, class: "default float-left warning button search_button" %>

<h3>Game Sessions</h3>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Session name</th>
      <th>Owner</th>
      <th>Number of players</th>
      <th>Effects used</th>
      <th>Passcode</th>
      <th>Effect buffer</th>
      <th>Lock player pages</th>
      <th>Player display mode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_sessions.each do |game_session| %>
      <tr>
        <td><%= game_session.id %></td>
        <td><%= game_session.session_name %></td>
        <td><%= game_session.owner %></td>
        <td><%= game_session.number_of_players %></td>
        <td><%= game_session.effects_used %></td>
        <td><%= game_session.passcode %></td>
        <td><%= game_session.effect_buffer %></td>
        <td><%= game_session.lock_player_pages %></td>
        <td><%= game_session.player_display_mode %></td>
        <td><%= link_to 'Show', game_session %></td>
        <td><%= link_to 'Edit', edit_game_session_path(game_session) %></td>
        <td><%= link_to 'Destroy', game_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game Session', new_game_session_path %>

app/views/game_sessions/my_sessions.html.erb
<h1>My Game Sessions</h1>

<table>
  <thead>
    <tr>
      <th>Session name</th>
      <th>Owner</th>
      <th>Number of players</th>
      <th>Effects used</th>
      <th>Passcode</th>
      <th>Effect buffer</th>
      <th>Lock player pages</th>
      <th>Player display mode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_sessions.each do |game_session| %>
      <tr>
        <td><%= link_to game_session.session_name, {:controller => "statics", :action => "dm_page", :id => game_session.id }, class: "" %></td>
        <td><%= game_session.owner %></td>
        <td><%= game_session.number_of_players %></td>
        <td><%= game_session.effects_used %></td>
        <td><%= game_session.passcode %></td>
        <td><%= game_session.effect_buffer %></td>
        <td><%= game_session.lock_player_pages %></td>
        <td><%= game_session.player_display_mode %></td>
        <td><%= link_to 'Show', game_session %></td>
        <td><%= link_to 'Edit', edit_game_session_path(game_session) %></td>
        <td><%= link_to 'Destroy', game_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game Session', new_game_session_path %>

app/views/game_sessions/new.html.erb
<div class="cell">
	<h3>New Game Session</h3>
</div>
<div>
<%= render 'form', game_session: @game_session %>
</div>
<div class="cell">
<%= link_to 'Back', game_sessions_path %>
</div>

app/views/game_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Session name:</strong>
  <%= @game_session.session_name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @game_session.owner %>
</p>

<p>
  <strong>Number of players:</strong>
  <%= @game_session.number_of_players %>
</p>

<p>
  <strong>Effects used:</strong>
  <%= @game_session.effects_used %>
</p>

<p>
  <strong>Passcode:</strong>
  <%= @game_session.passcode %>
</p>

<p>
  <strong>Effect buffer:</strong>
  <%= @game_session.effect_buffer %>
</p>

<p>
  <strong>Lock player pages:</strong>
  <%= @game_session.lock_player_pages %>
</p>

<p>
  <strong>Player display mode:</strong>
  <%= @game_session.player_display_mode %>
</p>

<%= link_to 'Edit', edit_game_session_path(@game_session) %> |
<%= link_to 'Back', game_sessions_path %>