config/routes.rb
Rails.application.routes.draw do
	resources :game_sessions
	resources :players
	resources :wands
	resources :durations
	resources :effects
	devise_for :users, :controllers => { registrations: 'registrations' }
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get '/settings' => 'statics#user_settings'
	get '/sessions' => 'game_sessions#my_sessions'
	get '/dm' => 'statics#dm_page'
	get '/p' => 'statics#player_page'
	root 'statics#dashboard'
end

app/models/duration.rb
class Duration < ApplicationRecord
end

app/controllers/durations_controller.rb
class DurationsController < ApplicationController
  before_action :set_duration, only: [:show, :edit, :update, :destroy]
  before_action :admin_check, only: [:index, :show, :edit, :update, :destroy]

  # GET /durations
  # GET /durations.json
  def index
    @durations = Duration.all
  end

  # GET /durations/1
  # GET /durations/1.json
  def show
  end

  # GET /durations/new
  def new
    @duration = Duration.new
  end

  # GET /durations/1/edit
  def edit
  end

  # POST /durations
  # POST /durations.json
  def create
    @duration = Duration.new(duration_params)

    respond_to do |format|
      if @duration.save
        format.html { redirect_to @duration, notice: 'Duration was successfully created.' }
        format.json { render :show, status: :created, location: @duration }
      else
        format.html { render :new }
        format.json { render json: @duration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /durations/1
  # PATCH/PUT /durations/1.json
  def update
    respond_to do |format|
      if @duration.update(duration_params)
        format.html { redirect_to @duration, notice: 'Duration was successfully updated.' }
        format.json { render :show, status: :ok, location: @duration }
      else
        format.html { render :edit }
        format.json { render json: @duration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /durations/1
  # DELETE /durations/1.json
  def destroy
    @duration.destroy
    respond_to do |format|
      format.html { redirect_to durations_url, notice: 'Duration was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_duration
      @duration = Duration.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def duration_params
      params.require(:duration).permit(:duration)
    end
end

app/helpers/durations_helper.rb
module DurationsHelper
end

app/views/durations/_form.html.erb
<%= form_with(model: duration, local: true) do |form| %>
  <% if duration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(duration.errors.count, "error") %> prohibited this duration from being saved:</h2>

      <ul>
      <% duration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :duration %>
    <%= form.text_field :duration %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/durations/edit.html.erb
<h1>Editing Duration</h1>

<%= render 'form', duration: @duration %>

<%= link_to 'Show', @duration %> |
<%= link_to 'Back', durations_path %>

app/views/durations/index.html.erb
<h1>Durations</h1>

<table>
  <thead>
    <tr>
      <th>Duration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @durations.each do |duration| %>
      <tr>
        <td><%= duration.duration %></td>
        <td><%= link_to 'Show', duration %></td>
        <td><%= link_to 'Edit', edit_duration_path(duration) %></td>
        <td><%= link_to 'Destroy', duration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Duration', new_duration_path %>

app/views/durations/new.html.erb
<h1>New Duration</h1>

<%= render 'form', duration: @duration %>

<%= link_to 'Back', durations_path %>

app/views/durations/show.html.erb
<p>
  <strong>Duration:</strong>
  <%= @duration.duration %>
</p>

<%= link_to 'Edit', edit_duration_path(@duration) %> |
<%= link_to 'Back', durations_path %>