config/routes.rb
Rails.application.routes.draw do
	resources :game_sessions
	resources :players
	resources :wands
	resources :durations
	resources :effects
	devise_for :users, :controllers => { registrations: 'registrations' }
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get '/settings' => 'statics#user_settings'
	get '/sessions' => 'game_sessions#my_sessions'
	get '/dm' => 'statics#dm_page'
	get '/p' => 'statics#player_page'
	root 'statics#dashboard'
end

app/models/effect.rb
class Effect < ApplicationRecord
end

app/controllers/effects_controller.rb
class EffectsController < ApplicationController
  before_action :set_effect, only: [:show, :edit, :update, :destroy]
  before_action :admin_check, only: [:index, :show, :edit, :update, :destroy]

  # GET /effects
  # GET /effects.json
  def index
    @effects = Effect.paginate(page: params[:page], per_page: 500)
  end

  # GET /effects/1
  # GET /effects/1.json
  def show
  end

  # GET /effects/new
  def new
    @effect = Effect.new
  end

  # GET /effects/1/edit
  def edit
  end

  # POST /effects
  # POST /effects.json
  def create
    @effect = Effect.new(effect_params)

    respond_to do |format|
      if @effect.save
        format.html { redirect_to @effect, notice: 'Effect was successfully created.' }
        format.json { render :show, status: :created, location: @effect }
      else
        format.html { render :new }
        format.json { render json: @effect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /effects/1
  # PATCH/PUT /effects/1.json
  def update
    respond_to do |format|
      if @effect.update(effect_params)
        format.html { redirect_to @effect, notice: 'Effect was successfully updated.' }
        format.json { render :show, status: :ok, location: @effect }
      else
        format.html { render :edit }
        format.json { render json: @effect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /effects/1
  # DELETE /effects/1.json
  def destroy
    @effect.destroy
    respond_to do |format|
      format.html { redirect_to effects_url, notice: 'Effect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_effect
      @effect = Effect.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def effect_params
      params.require(:effect).permit(:effect)
    end
end

app/helpers/effects_helper.rb
module EffectsHelper
end

app/views/effects/_form.html.erb
<%= form_with(model: effect, local: true) do |form| %>
  <% if effect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(effect.errors.count, "error") %> prohibited this effect from being saved:</h2>

      <ul>
      <% effect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :effect %>
    <%= form.text_field :effect %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/effects/edit.html.erb
<h1>Editing Effect</h1>

<%= render 'form', effect: @effect %>

<%= link_to 'Show', @effect %> |
<%= link_to 'Back', effects_path %>

app/views/effects/index.html.erb
<h1>Effects</h1>
<div class='cell'>
<%= will_paginate @effects, :container => false %>
</div>
<table>
  <thead>
    <tr>
      <th>Effect</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @effects.each do |effect| %>
      <tr>
        <td><%= effect.effect %></td>
        <td><%= link_to 'Show', effect %></td>
        <td><%= link_to 'Edit', edit_effect_path(effect) %></td>
        <td><%= link_to 'Destroy', effect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Effect', new_effect_path %>

app/views/effects/new.html.erb
<h1>New Effect</h1>

<%= render 'form', effect: @effect %>

<%= link_to 'Back', effects_path %>

app/views/effects/show.html.erb
<p>
  <strong>Effect:</strong>
  <%= @effect.effect %>
</p>

<%= link_to 'Edit', edit_effect_path(@effect) %> |
<%= link_to 'Back', effects_path %>