config/routes.rb
Rails.application.routes.draw do
	resources :game_sessions
	resources :players
	resources :wands
	resources :durations
	resources :effects
	devise_for :users, :controllers => { registrations: 'registrations' }
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	get '/settings' => 'statics#user_settings'
	get '/sessions' => 'game_sessions#my_sessions'
	get '/dm' => 'statics#dm_page'
	get '/p' => 'statics#player_page'
	root 'statics#dashboard'
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
	after_action :check_admin, only: [:user_settings]
	before_action :admin_check, only: [:user_settings]
	before_action :set_game_session, only: [:dm_page]

	def dashboard
	end

	def user_settings
		@users = User.all
	end

	def player_page
		@player = Player.where(unique_link: params[:p]).first
		@game_session = GameSession.find(@player.session_id)
		@wands = Wand.where(session_id: @game_session.id, player_id: @player.id).order(:id)
	end

	def dm_page

		@effects = Effect.random_records(@game_session_id.effect_buffer)
		@durations = Duration.random_records(@game_session_id.effect_buffer)
		@wand = Wand.new

		@description = Wand.generate_description()

		@players = Player.where(session_id: @game_session_id.id).order(:id)

		@players.each do |player|
			Rails.logger.info player.id.to_s + " | " + player.name.to_s + " | " + player.unique_link.to_s
			player_link_name = instance_variable_set("@#{"_" + player.unique_link.to_s}", Array.new)
			@wands = Wand.where(session_id: @game_session_id.id, player_id: player.id).order(:id)

			@wands.each do |wand|
				Rails.logger.info "Wand: " + wand.id.to_s + " | " + wand.effect.to_s
				player_link_name.push([wand.id, wand.uses_count, wand.effect_id, wand.effect, wand.duration, wand.description])
			end
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_game_session
		@game_session_id = GameSession.find(params[:id])
	end
end

app/views/statics/dashboard.html.erb
<ul>
<li><h3>User Controls Dashboard</h3></li>
<li><%= link_to 'New Game Session', new_game_session_url %></li>

<li><%= link_to 'My DM Sessions', sessions_path %></li>
<li>Player Session Screen</li>
<li><h3>Admin Dashboard</h3></li>
<li><%= link_to 'Durations', durations_path %></li>
<li><%= link_to 'Effects (warning: huge)', effects_path %></li>
<li><%= link_to 'Game Sessions', game_sessions_path %></li>
<li><%= link_to 'Wands', wands_path %></li>
<li><%= link_to 'Players', players_path %></li>
</ul>

app/views/statics/dm_page.html.erb
<div class="dm-page-accordian">
	<ul class="accordion" data-accordion>

		<li class="accordion-item" data-accordion-item>
			<a href="#" class="accordion-title">DM Info</a>
			<div class="accordion-content" data-tab-content>

			<p>Name: <%= @game_session_id.session_name %></p>
			<p>Owner: <%= User.find(@game_session_id.owner).email.to_s %></p>
			<p><%= link_to 'Edit Session', edit_game_session_path(@game_session_id) %></p>

			</div>
		</li>


		<li class="accordion-item is-active" data-accordion-item>
			<a href="#" class="accordion-title">
				Add New Wand
			</a>
			<div class="accordion-content" data-tab-content >

				If you need to reroll the effect buffer, refresh the page.
				<%= form_with(model: @wand, local: true) do |f| %>

				<%= f.select :player_id, options_from_collection_for_select(@players, "id", "name"), class: 'float-left' %>
				<%= f.select :effect_id, options_from_collection_for_select(@effects, "id", "effect"), class: 'float-left' %>
				<%= f.select :duration, options_from_collection_for_select(@durations, "id", "duration"), class: 'float-left' %>
				<%= f.hidden_field :session_id, value: @game_session_id.id %>
				<%= f.hidden_field :uses_count, value: 0 %>
				<%= f.label :description %>
				<%= f.text_field :description, value: @description %>
				<%= f.submit "Add Wand to Player" %>
				<% end %>

			</div>
		</li>

		<% @players.each do |player| %>

		<li class="accordion-item" data-accordion-item>
			<a href="#" class="accordion-title cell auto">
				<%= player.id %> | <%= player.name %>
			</a>
			<div class="accordion-content accordian-light" data-tab-content>
				<%= link_to "Edit Player", edit_player_path(player) %> | <%= link_to "Reset Player Wands", edit_player_path(player) %> | 
				<%= link_to "Player Page", {:controller => "statics", :action => "player_page", :p => player.unique_link }, class: "" %>

				 [Clipboard Copy]<span class="float-right">Unique ID: <%= player.unique_link %> [Clipboard Copy] </span>
			</div>		

			<% player_link_name = "@_" + player.unique_link.to_s %>
				<% if defined?(player_link_name) && player_link_name.present? %>
				<% Rails.logger.info "Hash for Player " + player.id.to_s + " does exist. | " + player_link_name.to_s  %>
				<% Rails.logger.info instance_variable_get(player_link_name) %>
				<% @player_wands = instance_variable_get(player_link_name) %>
					<% if @player_wands != [] %>
						<% @player_wands.each_with_index do |wands, i| %>

						<div class="accordion-content accordian-dark" data-tab-content>
							<%= (i+1).to_s %>. (#<%= wands[2] %>) <%= wands[3] %> |  <%= link_to "Delete", wand_path(wands[0]),  method: :delete  %>
						</div>
						<div class="accordion-content accordian-light" data-tab-content>
							<%= wands[5] %>
						</div>

						<% end %>
					<% else %>
						<div class="accordion-content accordian-light" data-tab-content>
							They have no wands, get more from the wizard.
						</div>
					<% end %>
				<% else %>
				<% Rails.logger.info "Hash for Player " + player.id.to_s + " does not exist! | " + player.unique_link.to_s %>
				<% end %>
		</li>

		<% end %>
	</ul>
</div>

app/views/statics/player_page.html.erb
<div class="cell">
Player Name: <%= @player.name %>
</div>
<ul class="accordion dm-page-accordian" data-accordion>
	<% @wands.each_with_index do |wand, i| %>

	<li class="accordion-item" data-accordion-item>
		<a href="#" class="accordion-title">
			#<%= (i+1).to_s %> | <%= wand.description %>
		</a>
		<% if @game_session.player_display_mode == true %>

		<div class="accordion-content" data-tab-content >
			Request DM to reveal wand effects
		</div>

		<% else %>

		<div class="accordion-content" data-tab-content >
			<p><%= wand.effect %></p>
			<p>Remaining Uses: XX</p>
		</div>

		<% end %>

	</li>

	<% end %>
</ul>

app/views/statics/user_settings.html.erb
<div class="cell">
	<h1>User Index</h1>
	<%= link_to 'Effects', effects_path, class: "button search_button" %>
	<%= link_to 'Durations', durations_path, class: "button search_button" %>
</div>
<table class="cell">
	<thead>
		<tr>
			<th>User</th>
			<th>Admin?</th>
			<th colspan='2'>Functions</th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user_item| %>
		<tr>
			<%= form_for :user_item do |f| %>
				<td class="">
					<%= user_item.id %> ) <%= user_item.email %>
				</td>
				<td>
					<%= user_item.admin %>
				</td>
				<td class=""> 
					<%= f.submit "Set User As Admin", class: "default button float-left" %>
				</td>
			<% end %>
		</tr>
		<% end %>
	</tbody>
</table>